services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrate:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://postgres@postgres/postgres?sslmode=disable", "up"]
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local