services:
  postgres:
    image: postgres:14.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
  app:
    image: registry.digitalocean.com/bookstop/bookstop:latest
    depends_on:
      - postgres
      - redis
    restart: on-failure
    env_file: .env
    ports:
      - "8080:80"
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local