package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"bookstop/models"
	"context"
	"fmt"
)

// Condition is the resolver for the condition field.
func (r *bookCopyResolver) Condition(ctx context.Context, obj *models.BookCopy) (string, error) {
	panic(fmt.Errorf("not implemented: Condition - condition"))
}

// Owners is the resolver for the owners field.
func (r *bookCopyResolver) Owners(ctx context.Context, obj *models.BookCopy) ([]*models.User, error) {
	panic(fmt.Errorf("not implemented: Owners - owners"))
}

// BookCopy returns BookCopyResolver implementation.
func (r *Resolver) BookCopy() BookCopyResolver { return &bookCopyResolver{r} }

type bookCopyResolver struct{ *Resolver }
