package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"bookstop/models"
	"context"
	"strconv"
)

// Books is the resolver for the books field.
func (r *browseResolver) Books(ctx context.Context, obj *models.Browse) ([]*models.Book, error) {
	return models.FindBrowseBooks(ctx, obj.ID)
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*models.Book, error) {
	idNum, _ := strconv.Atoi(id)
	return models.FindBookByID(ctx, idNum)
}

// BookSearch is the resolver for the bookSearch field.
func (r *queryResolver) BookSearch(ctx context.Context, query string, limit int, skip int) ([]*models.Book, error) {
	return models.SearchBooks(ctx, query, limit, skip)
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string) (*models.Author, error) {
	numId, _ := strconv.Atoi(id)
	return models.FindAuthorByID(ctx, numId)
}

// Genre is the resolver for the genre field.
func (r *queryResolver) Genre(ctx context.Context, id string) (*models.Genre, error) {
	numId, _ := strconv.Atoi(id)
	return models.FindGenreByID(ctx, numId)
}

// Genres is the resolver for the genres field.
func (r *queryResolver) Genres(ctx context.Context) ([]*models.Genre, error) {
	return models.FindAllGenres(ctx)
}

// Browses is the resolver for the browses field.
func (r *queryResolver) Browses(ctx context.Context) ([]*models.Browse, error) {
	return models.FindAllBrowses(ctx)
}

// Browse returns BrowseResolver implementation.
func (r *Resolver) Browse() BrowseResolver { return &browseResolver{r} }

type browseResolver struct{ *Resolver }

