package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"bookstop/models"
	"context"
	"fmt"
)

// Exchange is the resolver for the exchange field.
func (r *mutationResolver) Exchange(ctx context.Context, bookCopyID []string) (*models.Invoice, error) {
	panic(fmt.Errorf("not implemented: Exchange - exchange"))
}

// BookCopiesAvailable is the resolver for the bookCopiesAvailable field.
func (r *queryResolver) BookCopiesAvailable(ctx context.Context, bookID string) ([]*models.BookCopy, error) {
	panic(fmt.Errorf("not implemented: BookCopiesAvailable - bookCopiesAvailable"))
}

// MeInvoices is the resolver for the meInvoices field.
func (r *queryResolver) MeInvoices(ctx context.Context) ([]*models.Invoice, error) {
	panic(fmt.Errorf("not implemented: MeInvoices - meInvoices"))
}
