package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"bookstop/models"
	"context"
	"fmt"
)

// Location is the resolver for the location field.
func (r *queryResolver) Location(ctx context.Context, id string) (*models.Location, error) {
	panic(fmt.Errorf("not implemented: Location - location"))
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context) ([]*models.Location, error) {
	panic(fmt.Errorf("not implemented: Locations - locations"))
}
