package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"bookstop/auth"
	"bookstop/models"
	"context"
	"fmt"
	"strconv"
	"time"
)

// UserBookAdd is the resolver for the userBookAdd field.
func (r *mutationResolver) UserBookAdd(ctx context.Context, bookID string, startDate *string, endDate *string) (*models.UserBook, error) {
	usr, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if usr == nil {
		return nil, auth.ErrUnauthorized
	}

	bookIDNum, _ := strconv.Atoi(bookID)
	userBook := models.UserBook{
		BookID:    bookIDNum,
		UserID:    usr.ID,
		StartDate: startDate,
		EndDate:   endDate,
	}

	return models.CreateUserBook(ctx, &userBook)
}

// UserBookEdit is the resolver for the userBookEdit field.
func (r *mutationResolver) UserBookEdit(ctx context.Context, id string, startDate *string, endDate *string) (*models.UserBook, error) {
	usr, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if usr == nil {
		return nil, auth.ErrUnauthorized
	}
	idNum, _ := strconv.Atoi(id)
	userBook, err := models.FindUserBookByID(ctx, idNum)
	if err != nil {
		return nil, err
	}
	if userBook == nil {
		return nil, fmt.Errorf("userBook not found")
	}
	if userBook.IsOwner(usr.ID) == false {
		return nil, auth.ErrUnauthorized
	}
	userBook.StartDate = startDate
	userBook.EndDate = endDate

	return models.UpdateUserBook(ctx, userBook)
}

// UserBookDelete is the resolver for the userBookDelete field.
func (r *mutationResolver) UserBookDelete(ctx context.Context, id string) (bool, error) {
	usr, err := auth.ForContext(ctx)
	if err != nil {
		return false, err
	}
	if usr == nil {
		return false, auth.ErrUnauthorized
	}
	idNum, _ := strconv.Atoi(id)
	userBook, err := models.FindUserBookByID(ctx, idNum)
	if err != nil {
		return false, err
	}
	if userBook == nil {
		return false, fmt.Errorf("userBook not found")
	}
	if userBook.IsOwner(usr.ID) == false {
		return false, auth.ErrUnauthorized
	}

	err = models.DeleteUserBook(ctx, userBook.ID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// UserBook is the resolver for the userBook field.
func (r *queryResolver) UserBook(ctx context.Context, id string) (*models.UserBook, error) {
	idNum, _ := strconv.Atoi(id)
	return models.FindUserBookByID(ctx, idNum)
}

// UserBooks is the resolver for the userBooks field.
func (r *queryResolver) UserBooks(ctx context.Context, userID *string) ([]*models.UserBook, error) {
	if userID == nil {
		panic(fmt.Errorf("not implemented: UserBooks - without userID"))
	}
	idNum, _ := strconv.Atoi(*userID)
	return models.FindUserBooksByUserID(ctx, idNum)
}

// Owners is the resolver for the owners field.
func (r *userBookResolver) Owners(ctx context.Context, obj *models.UserBook) ([]*models.User, error) {
	if obj.BookCopyID == nil {
		return make([]*models.User, 0), nil
	}
	return models.FindBookCopyOwners(ctx, *obj.BookCopyID)
}

// UserBook returns UserBookResolver implementation.
func (r *Resolver) UserBook() UserBookResolver { return &userBookResolver{r} }

type userBookResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *userBookResolver) StartDate(ctx context.Context, obj *models.UserBook) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: StartDate - startDate"))
}
func (r *userBookResolver) EndDate(ctx context.Context, obj *models.UserBook) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: EndDate - endDate"))
}
