// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Book struct {
	ID            string   `json:"id"`
	Title         string   `json:"title"`
	Subtitle      *string  `json:"subtitle"`
	Authors       []string `json:"authors"`
	Description   string   `json:"description"`
	PublishedYear int      `json:"publishedYear"`
	ImageURL      *string  `json:"imageUrl"`
	Isbn          *string  `json:"isbn"`
}

type Browse struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ImageURL    *string `json:"imageUrl"`
}

type User struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	ProfileImageURL *string   `json:"profileImageUrl"`
	CreatedAt       time.Time `json:"createdAt"`
}

type UserBook struct {
	ID                 string    `json:"id"`
	BookID             string    `json:"bookId"`
	Book               *Book     `json:"book"`
	UserID             string    `json:"userId"`
	StartedAt          *string   `json:"startedAt"`
	EndedAt            *string   `json:"endedAt"`
	OriginalUserBookID *string   `json:"originalUserBookId"`
	OriginalUserBook   *UserBook `json:"originalUserBook"`
}
